ARTICLES = [
    {
        "title": "US Inflation Surges to 4.2% as Fed Faces Policy Dilemma",
        "body": "Consumer prices in the United States rose 4.2% year-over-year in February 2026, exceeding expectations of 3.8%. Core inflation, excluding food and energy, climbed to 3.9%. The Federal Reserve now faces a difficult choice between maintaining its fight against inflation and supporting an economy showing signs of slowing growth. Markets are repricing rate cut expectations, with the first cut now pushed to Q4 2026.",
        "source": "Reuters",
        "date": "2026-03-01",
    },
    {
        "title": "ECB Cuts Rates by 25bps, Signals More Easing Ahead",
        "body": "The European Central Bank lowered its key interest rate by 25 basis points to 2.5%, citing weakening economic growth across the eurozone. President Lagarde indicated further cuts are likely if inflation continues its downward trajectory. The euro fell 0.8% against the dollar following the announcement. European bond yields dropped sharply, with the German 10-year bund falling below 2%.",
        "source": "Bloomberg",
        "date": "2026-02-28",
    },
    {
        "title": "China Announces $500B Stimulus Package Targeting Property Sector",
        "body": "China's State Council unveiled a 3.6 trillion yuan ($500 billion) stimulus package aimed at stabilizing the property sector and boosting domestic consumption. The package includes direct subsidies for homebuyers, reduced down payment requirements, and local government debt restructuring. Analysts say the measures could lift GDP growth by 0.5-0.8 percentage points but warn about long-term debt sustainability.",
        "source": "Financial Times",
        "date": "2026-03-03",
    },
    {
        "title": "Bank of Japan Raises Rates to 0.75%, Yen Strengthens Sharply",
        "body": "The Bank of Japan raised its benchmark interest rate by 25 basis points to 0.75%, the highest level since 2008. Governor Ueda cited persistent wage growth and inflation above the 2% target. The yen surged 2.3% against the dollar, and Japanese government bond yields rose to multi-year highs. The move has significant implications for global carry trades and emerging market flows.",
        "source": "Nikkei Asia",
        "date": "2026-03-02",
    },
    {
        "title": "UK GDP Contracts 0.3% as Recession Fears Mount",
        "body": "The United Kingdom's economy contracted by 0.3% in Q4 2025, raising fears of a technical recession. The services sector, which accounts for 80% of UK GDP, showed particular weakness. The Bank of England is now under pressure to accelerate rate cuts despite inflation remaining above target at 3.1%. Sterling fell to its lowest level against the dollar since October 2024.",
        "source": "The Guardian",
        "date": "2026-02-25",
    },
    {
        "title": "Middle East Tensions Escalate: Oil Prices Spike Above $95",
        "body": "Brent crude surged above $95 per barrel after escalating tensions in the Middle East disrupted shipping through the Strait of Hormuz. Iran-backed forces launched attacks on commercial vessels, prompting a US naval response. Energy analysts warn that sustained disruption could push oil above $100, adding inflationary pressure globally. OPEC+ has declined to increase production quotas.",
        "source": "CNBC",
        "date": "2026-03-04",
    },
    {
        "title": "India's GDP Growth Accelerates to 7.8%, Outpaces China",
        "body": "India reported GDP growth of 7.8% for Q4 2025, making it the fastest-growing major economy. Strong manufacturing expansion, digital infrastructure investment, and robust domestic consumption drove the performance. Foreign direct investment inflows reached record levels. The Reserve Bank of India maintained its repo rate at 6.5%, balancing growth with inflation control.",
        "source": "Economic Times",
        "date": "2026-02-27",
    },
    {
        "title": "Brazil Central Bank Holds Rates at 13.75% Despite Political Pressure",
        "body": "Brazil's central bank maintained its benchmark Selic rate at 13.75% despite President Lula's repeated calls for rate cuts. The bank cited persistent core inflation and fiscal concerns related to increased government spending. The real weakened slightly against the dollar. Market participants expect the first rate cut no earlier than June 2026.",
        "source": "Valor Econômico",
        "date": "2026-03-01",
    },
    {
        "title": "US-China Tech Tensions: New Semiconductor Export Controls Announced",
        "body": "The US Commerce Department announced expanded semiconductor export controls targeting China's AI chip development. The new rules restrict sales of advanced GPU architectures and chipmaking equipment. China vowed retaliatory measures against US tech companies operating in its market. The move sent shockwaves through global semiconductor supply chains, with chip stocks falling 4-7%.",
        "source": "Wall Street Journal",
        "date": "2026-03-03",
    },
    {
        "title": "German Manufacturing PMI Hits 18-Month Low at 43.2",
        "body": "Germany's manufacturing PMI fell to 43.2 in February, its lowest reading in 18 months. New orders declined sharply, particularly from China, while energy costs remained elevated. The data reinforces concerns about Europe's largest economy potentially entering recession. German industrial production has now declined for three consecutive quarters.",
        "source": "Reuters",
        "date": "2026-03-01",
    },
    {
        "title": "Australia's Housing Crisis Deepens: RBA Faces Impossible Trade-off",
        "body": "Australian home prices surged 12% year-over-year amid chronic supply shortages, while household debt reached record levels. The Reserve Bank of Australia faces a dilemma: raising rates to cool housing risks crushing consumer spending, while holding steady fuels further price gains. Immigration policy and zoning reform are increasingly seen as the only structural solutions.",
        "source": "Sydney Morning Herald",
        "date": "2026-02-26",
    },
    {
        "title": "Swiss National Bank Intervenes to Weaken Franc Amid Safe-Haven Flows",
        "body": "The Swiss National Bank conducted significant currency interventions to stem the franc's appreciation, which reached record levels against the euro. Global uncertainty drove safe-haven flows into Swiss assets. The SNB warned that an overvalued franc threatens export competitiveness and could push the economy into deflation. Swiss government bond yields turned negative again.",
        "source": "SWI swissinfo",
        "date": "2026-03-02",
    },
    {
        "title": "South Korea's Export Boom: Semiconductor Revenues Hit Record",
        "body": "South Korea's exports surged 18% year-over-year in February, driven by record semiconductor sales fueled by global AI demand. Samsung and SK Hynix reported order backlogs extending through 2026. The won strengthened, and the KOSPI index rose 3.2%. However, analysts warn that US-China tech tensions could disrupt supply chains and impact future orders.",
        "source": "Korea Herald",
        "date": "2026-03-02",
    },
    {
        "title": "Turkey's Lira Crisis: Inflation Hits 58% as Confidence Collapses",
        "body": "Turkey's annual inflation rate surged to 58% in February, driven by lira depreciation and loose fiscal policy ahead of local elections. The central bank raised rates by 500 basis points to 50% in an emergency session. Capital flight accelerated as foreign investors pulled $2.3 billion from Turkish assets in a single week. The IMF urged fiscal consolidation.",
        "source": "Al Jazeera",
        "date": "2026-02-28",
    },
    {
        "title": "Canada Housing Correction Accelerates: Prices Down 15% from Peak",
        "body": "Canadian home prices have now fallen 15% from their 2024 peak, with Toronto and Vancouver leading the decline. Rising mortgage rates and tighter lending standards have cooled demand. The Bank of Canada cut rates by 25bps but warned that further easing depends on inflation progress. Construction sector layoffs are mounting, with 45,000 jobs lost in Q4 2025.",
        "source": "Globe and Mail",
        "date": "2026-02-27",
    },
    {
        "title": "Nigeria's Naira Stabilizes After Central Bank Reforms",
        "body": "Nigeria's naira has stabilized around 1,200 per dollar after the central bank implemented sweeping forex market reforms. The unified exchange rate system and removal of fuel subsidies have attracted $4.2 billion in foreign portfolio investment. However, inflation remains at 28% and poverty levels have increased. The World Bank approved a $2.5 billion development package.",
        "source": "Business Day Nigeria",
        "date": "2026-03-01",
    },
    {
        "title": "EU Carbon Border Tax Takes Effect: Trade Partners React",
        "body": "The European Union's Carbon Border Adjustment Mechanism (CBAM) entered full implementation, imposing tariffs on carbon-intensive imports including steel, aluminum, and cement. China, India, and Turkey called the measure protectionist and threatened WTO challenges. European manufacturers gained competitive advantages, but downstream industries face higher input costs. The tax is expected to generate €14 billion annually.",
        "source": "Politico EU",
        "date": "2026-03-04",
    },
    {
        "title": "Mexico Nearshoring Boom: FDI Doubles as Supply Chains Shift",
        "body": "Foreign direct investment in Mexico doubled year-over-year to $42 billion in 2025, driven by companies relocating manufacturing from China. The automotive, electronics, and aerospace sectors led the surge. Northern border states saw industrial real estate vacancy rates fall below 2%. The peso strengthened to its highest level since 2015, though Banxico warned about overheating risks.",
        "source": "El Financiero",
        "date": "2026-02-26",
    },
    {
        "title": "Global Sovereign Debt Hits $100 Trillion: IMF Warns of Fiscal Cliff",
        "body": "Global sovereign debt surpassed $100 trillion for the first time, with the US, Japan, and China accounting for over 60% of the total. The IMF warned that rising interest costs are crowding out essential spending and increasing vulnerability to financial shocks. Several emerging markets face refinancing walls in 2026-2027, with $800 billion in dollar-denominated debt maturing.",
        "source": "IMF Blog",
        "date": "2026-03-03",
    },
    {
        "title": "Saudi Arabia Announces $1 Trillion Diversification Fund",
        "body": "Saudi Arabia launched a $1 trillion sovereign wealth fund focused on post-oil economic diversification. Priority sectors include AI, biotechnology, tourism, and renewable energy. The fund will invest 40% domestically and 60% internationally. Aramco's partial privatization will fund initial commitments. The move signals acceleration of Vision 2030 and has implications for global capital flows.",
        "source": "Arab News",
        "date": "2026-03-04",
    },
    {
        "title": "Vietnam's Tech Manufacturing Sector Attracts Apple, NVIDIA",
        "body": "Vietnam secured major manufacturing commitments from Apple and NVIDIA, positioning itself as a key alternative to China in the global tech supply chain. The government approved $8 billion in infrastructure upgrades to support new factories. Vietnam's GDP is projected to grow 7.2% in 2026. However, skilled labor shortages and power grid limitations remain challenges.",
        "source": "VnExpress",
        "date": "2026-02-28",
    },
    {
        "title": "Argentina Dollarization Debate Intensifies as Peso Collapses",
        "body": "Argentina's peso fell 30% in a single month, reigniting the dollarization debate. President Milei's austerity measures have reduced the fiscal deficit but at the cost of a severe recession. GDP contracted 5.2% year-over-year. The IMF approved a $7 billion disbursement tied to further reforms. Poverty rates exceeded 40%, fueling social unrest.",
        "source": "La Nación",
        "date": "2026-03-02",
    },
    {
        "title": "Bank of England Cuts Rates to 4.0% in Split Decision",
        "body": "The Bank of England reduced its benchmark rate by 25 basis points to 4.0% in a 5-4 split decision. Dovish members cited recession risks, while hawks pointed to persistent services inflation at 5.2%. Governor Bailey struck a cautious tone, emphasizing data dependency. UK gilt yields fell, and mortgage rates are expected to decline gradually through Q2 2026.",
        "source": "Financial Times",
        "date": "2026-03-01",
    },
    {
        "title": "Indonesia Restricts Nickel Exports: EV Battery Costs Set to Rise",
        "body": "Indonesia, the world's largest nickel producer, announced export restrictions on raw nickel ore to force domestic processing. The move is expected to increase global nickel prices by 15-20% and raise EV battery production costs. Tesla and BYD are accelerating investments in Indonesian smelting facilities. The policy mirrors Indonesia's successful palm oil processing strategy.",
        "source": "Jakarta Post",
        "date": "2026-03-03",
    },
    {
        "title": "Federal Reserve Minutes Reveal Deep Divisions on Rate Path",
        "body": "Minutes from the Federal Reserve's January meeting revealed significant disagreement among policymakers about the future rate path. Several members favored signaling rate cuts by mid-2026, while others argued inflation risks warranted maintaining current levels through year-end. The debate reflects broader uncertainty about whether the US economy faces a soft landing or stagflation scenario.",
        "source": "Associated Press",
        "date": "2026-02-26",
    },
]
